version: '3'

services:
    bot:
        container_name: slack-translate
        restart: always
        hostname: slack-translate.local
        build:
            dockerfile: Dockerfile
            context: .
        depends_on:
            - redis
        volumes:
            - ..:/workspace:cached
        command: sleep infinity
        ports: 
            - "8080:80"
    redis:
        container_name: slack-translate-cache
        image: redis:latest
        volumes:
            - redis:/data
        ports:
            - "6379:6379"
    
volumes:
    redis:
    bot: